root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
telegram.ext.dispatcher - WARNING - A TelegramError was raised while processing the Update
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/ext/conversationhandler.py", line 305, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/ext/callbackqueryhandler.py", line 143, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/dmitriy/projects/diplom/bot_diplom.py", line 259, in calendar
    reply_markup=choose_master(bot, update, user_data))
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/utils/request.py", line 223, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Object expected as reply markup
telegram.ext.dispatcher - WARNING - A TelegramError was raised while processing the Update
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/ext/conversationhandler.py", line 305, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/ext/callbackqueryhandler.py", line 143, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/dmitriy/projects/diplom/bot_diplom.py", line 263, in calendar
    reply_markup=choose_master(bot, update, user_data))
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/utils/request.py", line 223, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Object expected as reply markup
telegram.ext.dispatcher - WARNING - A TelegramError was raised while processing the Update
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/ext/conversationhandler.py", line 305, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/ext/callbackqueryhandler.py", line 143, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/dmitriy/projects/diplom/bot_diplom.py", line 255, in calendar
    reply_markup=choose_master(bot, update, user_data))
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/utils/request.py", line 223, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Object expected as reply markup
telegram.ext.dispatcher - WARNING - A TelegramError was raised while processing the Update
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/ext/conversationhandler.py", line 305, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/ext/callbackqueryhandler.py", line 143, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/dmitriy/projects/diplom/bot_diplom.py", line 259, in calendar
    reply_markup=choose_master(bot, update, user_data))
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/utils/request.py", line 223, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Object expected as reply markup
telegram.ext.dispatcher - WARNING - A TelegramError was raised while processing the Update
telegram.ext.dispatcher - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/ext/dispatcher.py", line 279, in process_update
    handler.handle_update(update, self)
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/ext/conversationhandler.py", line 305, in handle_update
    new_state = self.current_handler.handle_update(update, dispatcher)
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/ext/callbackqueryhandler.py", line 143, in handle_update
    return self.callback(dispatcher.bot, update, **optional_args)
  File "/Users/dmitriy/projects/diplom/bot_diplom.py", line 263, in calendar
    reply_markup=choose_master(bot, update, user_data))
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/bot.py", line 65, in decorator
    result = func(self, *args, **kwargs)
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/bot.py", line 90, in decorator
    result = self._request.post(url, data, timeout=kwargs.get('timeout'))
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/utils/request.py", line 309, in post
    headers={'Content-Type': 'application/json'})
  File "/Users/dmitriy/projects/diplom/env/lib/python3.6/site-packages/telegram/utils/request.py", line 223, in _request_wrapper
    raise BadRequest(message)
telegram.error.BadRequest: Object expected as reply markup
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
root - WARNING - If 'per_message=False', 'CallbackQueryHandler' will not be tracked for every message.
telegram.ext.updater - INFO - Received signal 2 (SIGINT), stopping...
telegram.ext.updater - WARNING - Exiting immediately!
